name: Build and Push Ollama Model Image

on:
  workflow_dispatch:
    inputs:
      model_name:
        type: string
        description: '模型名称（例如：qwen3:1.7b）'
        required: true

env:
  IMAGE_NAME: ${{ secrets.IMAGE_NAME }}        # registry.cn-hangzhou.aliyuncs.com/mine/ollama
  REGISTRY_USER: ${{ secrets.REGISTRY_USER }} # 阿里云账号或 AccessKey ID
  REGISTRY_PASS: ${{ secrets.REGISTRY_PASS }} # 阿里云 AccessKey Secret 或密码

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Replace Colon in Model Name
        id: tag
        run: |
          # 替换模型名中的冒号为下划线
          MODEL_NAME=${{ github.event.inputs.model_name }}
          TAG=${MODEL_NAME//:/_}
          echo "TAG=$TAG" >> $GITHUB_ENV

      - name: Login to Alibaba Cloud Container Registry
        run: |
          echo "${{ secrets.REGISTRY_PASS }}" | docker login $IMAGE_NAME \
            -u "${{ secrets.REGISTRY_USER }}" \
            --password-stdin

      - name: Build Docker Image with Model
        run: |
          docker build \
            --build-arg MODEL_NAME=${{ github.event.inputs.model_name }} \
            -t $IMAGE_NAME:${{ env.TAG }} .

      - name: Push Docker Image
        run: |
          docker push $IMAGE_NAME:${{ env.TAG }}

      - name: Clean up
        run: |
          docker rmi $IMAGE_NAME:${{ env.TAG }} || true
